### ISSUE TITLE
Distinction between AngularJS & Angular

### ISSUE THREAD

**Issue by PaulIvanov** [StateOfJS/State-of-JS-2019#28]
It wasnt clear if there is a distinction between these 2 frameworks throughout the statistics

**Comment by Daniel15** [comment]
Huh... TIL "AngularJS" refers to v1, whereas "Angular" refers to v2 and any future versions. That's confusing 😄 

> Upgrading from AngularJS to Angular
>
> Angular is the name for the Angular of today and tomorrow.
> AngularJS is the name for all 1.x versions of Angular.

https://angular.io/guide/upgrade

**Comment by OrangeDuck91** [comment]
I agree there is a problem. In the questions, there wasn't two disctinct choices beetween AngularJs and Angular 2+, wich are in my opinion two different frameworks. Problem is, lots of JS dev still use AngularJs and don't like it (I can understand why), and on this survey the only way to tell it is to say "Angular is bad". That's why I take all the Angular results with a big pinch salt.

**Comment by SachaG** [comment]
Yes it's been discussed a lot, see here: https://github.com/StateOfJS/StateOfJS-Vulcan/issues/26

Basically our reasoning is that AngularJS is older and less popular, and we tend to remove those technologies from the survey as time goes by to keep it shorter (see also: the lack of Backbone, Knockout, etc.). 

This leaves only Angular remaining. I see how it can be confusing but I don't think we can be blamed for that confusion when we are only using the framework's own official name.
