### ISSUE TITLE
Flow excluded from statistics

### ISSUE THREAD

**Issue by 0rvar** [StateOfJS/State-of-JS-2019#49]
Why was flow excluded from the main statistics, instead dumped into "Other Flavors"? Would have been interesting to see how Flow popularity and opinions have changes compared to TS, especially in the overview.

**Comment by plouc** [comment]
We remove tools which (really) lost momentum/seem to be less and less used from the main options, I think you can compare the number of respondents who answered: *I've USED it before, and WOULD use it again* for TypeScript: `11780` VS the number of respondents who mentioned Flow: `276`. You can also compare those [numbers in 2018](https://2018.stateofjs.com/javascript-flavors/overview/), it seems most people have moved to TypeScript instead of Flow.
